NEXAOS_NAME="NexaOS"
NEXAOS_VERSION="0.1"
NEXAOS_CODENAME="Aurora"
NEXAOS_ARCH="amd64"

DEBIAN_RELEASE="bookworm"
DEBIAN_MIRROR="http://deb.debian.org/debian"

ROOTFS="$PWD/build/rootfs"
OUTPUT="$PWD/output"

NEXAOS_USER="nexa"
HOSTNAME="nexaos"
